name: Build

on:
  push:
    branches: [ "master" ]
    paths:
    - .github/workflows/build.yml
    - Technicolor/**
    - Technicolor.sln

jobs:
  build:
    name: Build
    strategy:
      matrix:
        game-version: [ 1.29.1, 1.34.2 ]
    uses: Aeroluna/workflows/.github/workflows/bs-build-version-release.yml@main
    with:
      project-path: Technicolor/Technicolor.csproj
      game-version: ${{ matrix.game-version }}
      additional-sources: '["Aeroluna/Heck"]'
    secrets: inherit

  create_release:
    name: Create Release
    needs: build
    permissions:
      contents: write
    uses: Aeroluna/workflows/.github/workflows/bs-create-release-from-date.yml@main
    with:
      project-path: Technicolor/Technicolor.csproj
    secrets: inherit
